# Generated by Django 3.2.4 on 2021-07-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_register_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Password',
        ),
    ]
